package admission.model.security;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Privileges generated by hbm2java
 */
@Entity
@Table(name = "YOG_LOG"
)
public class Log implements java.io.Serializable {

    private Integer id;
    private User user;
    private String modelName;
    private Integer modelId;
    private String modelAction;
    private Long logDate;
    private String remarks;

    public Log() {
    }

    public Log(User user, String modelName, Integer modelId, String modelAction, Long logDate, String remarks) {
        this.user = user;
        this.modelName = modelName;
        this.modelId = modelId;
        this.modelAction = modelAction;
        this.logDate = logDate;
        this.remarks = remarks;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "user_id", nullable = false)
    public User getUser() {
        return this.user;
    }

    public void setUser(User user) {
        this.user = user;
    }

    @Column(name = "MODEL_NAME", nullable = false)
    public String getModelName() {
        return modelName;
    }

    public void setModelName(String modelName) {
        this.modelName = modelName;
    }
    
    @Column(name = "MODEL_ID", nullable = false)
    public Integer getModelId() {
        return this.modelId;
    }

    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }
    
    @Column(name = "MODEL_ACTION", nullable = false)
    public String getModelAction() {
        return this.modelAction;
    }

    public void setModelAction(String modelAction) {
        this.modelAction = modelAction;
    }
    
    @Column(name = "LOG_DATE", nullable = false)
    public Long getLogDate() {
        return this.logDate;
    }

    public void setLogDate(Long logDate) {
        this.logDate = logDate;
    }
    
    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Override
    public String toString() {
        return modelName;
    }

}
