package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AdmissionSession generated by hbm2java
 */
@Entity
@Table(name = "admission_session"
)
public class AdmissionSession implements java.io.Serializable {

    private Integer admissionSessionId;
    private ProgramType programType;
    private AdmissionYear admissionYear;
    private String remarks;

    public AdmissionSession() {
    }

    public AdmissionSession(ProgramType programType, AdmissionYear admissionYear) {
        this.programType = programType;
        this.admissionYear = admissionYear;
    }

    public AdmissionSession(ProgramType programType, AdmissionYear admissionYear, String remarks) {
        this.programType = programType;
        this.admissionYear = admissionYear;
        this.remarks = remarks;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "admission_session_id", unique = true, nullable = false)
    public Integer getAdmissionSessionId() {
        return this.admissionSessionId;
    }

    public void setAdmissionSessionId(Integer admissionSessionId) {
        this.admissionSessionId = admissionSessionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "program_type_id", nullable = false)
    public ProgramType getProgramType() {
        return this.programType;
    }

    public void setProgramType(ProgramType programType) {
        this.programType = programType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admission_year_id", nullable = false)
    public AdmissionYear getAdmissionYear() {
        return this.admissionYear;
    }

    public void setAdmissionYear(AdmissionYear admissionYear) {
        this.admissionYear = admissionYear;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Override
    public String toString() {
        return this.getProgramType().toString();
    }

}
