package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * AdmissionYear generated by hbm2java
 */
@Entity
@Table(name = "admission_year"
)
public class AdmissionYear implements java.io.Serializable {

    private Integer admissionYearId;
    private Integer year;
    private String remarks;
    private Set<AdmissionSession> admissionSessions = new HashSet<AdmissionSession>(0);
    private Set<Test> tests = new HashSet<Test>(0);
    private Set<DistrictSeatDistribution> districtSeatDistributions = new HashSet<DistrictSeatDistribution>(0);
    private Set<Candidate> candidates = new HashSet<Candidate>(0);

    public AdmissionYear() {
    }

    public AdmissionYear(Integer year, String remarks, Set<AdmissionSession> admissionSessions, Set<Test> tests, Set<DistrictSeatDistribution> districtSeatDistributions, Set<Candidate> candidates) {
        this.year = year;
        this.remarks = remarks;
        this.admissionSessions = admissionSessions;
        this.tests = tests;
        this.districtSeatDistributions = districtSeatDistributions;
        this.candidates = candidates;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "admission_year_id", unique = true, nullable = false)
    public Integer getAdmissionYearId() {
        return this.admissionYearId;
    }

    public void setAdmissionYearId(Integer admissionYearId) {
        this.admissionYearId = admissionYearId;
    }

    @Column(name = "year")
    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "admissionYear")
    public Set<AdmissionSession> getAdmissionSessions() {
        return this.admissionSessions;
    }

    public void setAdmissionSessions(Set<AdmissionSession> admissionSessions) {
        this.admissionSessions = admissionSessions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "admissionYear")
    public Set<Test> getTests() {
        return this.tests;
    }

    public void setTests(Set<Test> tests) {
        this.tests = tests;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "admissionYear")
    public Set<DistrictSeatDistribution> getDistrictSeatDistributions() {
        return this.districtSeatDistributions;
    }

    public void setDistrictSeatDistributions(Set<DistrictSeatDistribution> districtSeatDistributions) {
        this.districtSeatDistributions = districtSeatDistributions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "admissionYear")
    public Set<Candidate> getCandidates() {
        return this.candidates;
    }

    public void setCandidates(Set<Candidate> candidates) {
        this.candidates = candidates;
    }

    @Override
    public String toString() {
        return String.valueOf(this.getYear());
    }

}
