package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AdmissionList generated by hbm2java
 */
@Entity
@Table(name = "admission_list"
)
public class AdmissionList implements java.io.Serializable {

    private Integer admissionListId;
    private AdmissionSession admissionSession;
    private Campus campus;
    private Integer listNo;
    private Date obDateFrom;
    private Date obDateTo;
    private String remarks;
    private boolean isManual;
    private Set<AdmissionListDetails> admissionListDetailses = new HashSet<AdmissionListDetails>(0);

    public AdmissionList() {
    }

    public AdmissionList(AdmissionSession admissionSession, Campus campus, boolean isManual) {
        this.admissionSession = admissionSession;
        this.campus = campus;
        this.isManual = isManual;
    }

    public AdmissionList(AdmissionSession admissionSession, Campus campus, Integer listNo, Date obDateFrom, Date obDateTo, String remarks, boolean isManual, Set<AdmissionListDetails> admissionListDetailses) {
        this.admissionSession = admissionSession;
        this.campus = campus;
        this.listNo = listNo;
        this.obDateFrom = obDateFrom;
        this.obDateTo = obDateTo;
        this.remarks = remarks;
        this.isManual = isManual;
        this.admissionListDetailses = admissionListDetailses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "admission_list_id", unique = true, nullable = false)
    public Integer getAdmissionListId() {
        return this.admissionListId;
    }

    public void setAdmissionListId(Integer admissionListId) {
        this.admissionListId = admissionListId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admission_session_id", nullable = false)
    public AdmissionSession getAdmissionSession() {
        return this.admissionSession;
    }

    public void setAdmissionSession(AdmissionSession admissionSession) {
        this.admissionSession = admissionSession;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "campus_id", nullable = false)
    public Campus getCampus() {
        return this.campus;
    }

    public void setCampus(Campus campus) {
        this.campus = campus;
    }

    @Column(name = "list_no")
    public Integer getListNo() {
        return this.listNo;
    }

    public void setListNo(Integer listNo) {
        this.listNo = listNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ob_date_from", length = 10)
    public Date getObDateFrom() {
        return this.obDateFrom;
    }

    public void setObDateFrom(Date obDateFrom) {
        this.obDateFrom = obDateFrom;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "ob_date_to", length = 10)
    public Date getObDateTo() {
        return this.obDateTo;
    }

    public void setObDateTo(Date obDateTo) {
        this.obDateTo = obDateTo;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "is_manual", nullable = false)
    public boolean isIsManual() {
        return this.isManual;
    }

    public void setIsManual(boolean isManual) {
        this.isManual = isManual;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "admissionList")
    public Set<AdmissionListDetails> getAdmissionListDetailses() {
        return this.admissionListDetailses;
    }

    public void setAdmissionListDetailses(Set<AdmissionListDetails> admissionListDetailses) {
        this.admissionListDetailses = admissionListDetailses;
    }

    @Override
    public String toString() {
        String s = ((isManual) ? " (M)" : "");
        return "List " + this.getListNo() + s;
    }

}
