package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import admission.enums.SelectionStatusEnum;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * AdmissionListDetails generated by hbm2java
 */
@Entity
@Table(name = "admission_list_details"
)
public class AdmissionListDetails implements java.io.Serializable {

    private int candidateId;
    private String posName;
    private int posPCode;
    private String cposg;
    private String campusCategoryName;
    private int choiceNo;
    private String shiftName;

    private Integer admissionListDetailsId;
    private Candidate candidate;
    private CandidateProgramOfStudy candidateProgramOfStudy;
    private CampusCategory campusCategory;
    private CposGroup cposGroup;
    private AdmissionList admissionList;
    private SelectionStatusEnum status;
    private String remarks;
    private Boolean active;
    private Integer rollNo;
    private Set<PartRegistry> partRegistries = new HashSet<PartRegistry>(0);

    public AdmissionListDetails() {
    }

    public AdmissionListDetails(Candidate candidate, CandidateProgramOfStudy candidateProgramOfStudy, CampusCategory campusCategory, CposGroup cposGroup, AdmissionList admissionList) {
        this.candidate = candidate;
        this.candidateProgramOfStudy = candidateProgramOfStudy;
        this.campusCategory = campusCategory;
        this.cposGroup = cposGroup;
        this.admissionList = admissionList;
    }

    public AdmissionListDetails(Candidate candidate, CandidateProgramOfStudy candidateProgramOfStudy, CampusCategory campusCategory, CposGroup cposGroup, AdmissionList admissionList, SelectionStatusEnum status, String remarks, Boolean active, Integer rollNo, Set<PartRegistry> partRegistries) {
        this.candidate = candidate;
        this.candidateProgramOfStudy = candidateProgramOfStudy;
        this.campusCategory = campusCategory;
        this.cposGroup = cposGroup;
        this.admissionList = admissionList;
        this.status = status;
        this.remarks = remarks;
        this.active = active;
        this.rollNo = rollNo;
        this.partRegistries = partRegistries;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "admission_list_details_id", unique = true, nullable = false)
    public Integer getAdmissionListDetailsId() {
        return this.admissionListDetailsId;
    }

    public void setAdmissionListDetailsId(Integer admissionListDetailsId) {
        this.admissionListDetailsId = admissionListDetailsId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "candidate_id", nullable = false)
    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "candidate_program_of_study_id", nullable = false)
    public CandidateProgramOfStudy getCandidateProgramOfStudy() {
        return this.candidateProgramOfStudy;
    }

    public void setCandidateProgramOfStudy(CandidateProgramOfStudy candidateProgramOfStudy) {
        this.candidateProgramOfStudy = candidateProgramOfStudy;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "campus_category_id", nullable = false)
    public CampusCategory getCampusCategory() {
        return this.campusCategory;
    }

    public void setCampusCategory(CampusCategory campusCategory) {
        this.campusCategory = campusCategory;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cpos_group_id", nullable = false)
    public CposGroup getCposGroup() {
        return this.cposGroup;
    }

    public void setCposGroup(CposGroup cposGroup) {
        this.cposGroup = cposGroup;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admission_list_id", nullable = false)
    public AdmissionList getAdmissionList() {
        return this.admissionList;
    }

    public void setAdmissionList(AdmissionList admissionList) {
        this.admissionList = admissionList;
    }

    @Column(name = "status")
    @Enumerated
    public SelectionStatusEnum getStatus() {
        return this.status;
    }

    public void setStatus(SelectionStatusEnum status) {
        this.status = status;
    }

    @Column(name = "remarks", length = 256)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "active")
    public Boolean getActive() {
        return this.active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    @Column(name = "roll_no")
    public Integer getRollNo() {
        return this.rollNo;
    }

    public void setRollNo(Integer rollNo) {
        this.rollNo = rollNo;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "admissionListDetails")
    public Set<PartRegistry> getPartRegistries() {
        return this.partRegistries;
    }

    public void setPartRegistries(Set<PartRegistry> partRegistries) {
        this.partRegistries = partRegistries;
    }

    public void setCampusCategoryName(String campusCategoryName) {
        this.campusCategoryName = campusCategoryName;
    }

    @Transient
    public String getCampusCategoryName() {
        return campusCategoryName;
    }

    public void setCandidateId(int candidateId) {
        this.candidateId = candidateId;
    }

    @Transient
    public int getCandidateId() {
        return candidateId;
    }

    public void setChoiceNo(int choiceNo) {
        this.choiceNo = choiceNo;
    }

    @Transient
    public int getChoiceNo() {
        return choiceNo;
    }

    public void setCposg(String cposg) {
        this.cposg = cposg;
    }

    @Transient
    public String getCposg() {
        return cposg;
    }

    public void setPosName(String posName) {
        this.posName = posName;
    }

    @Transient
    public String getPosName() {
        return posName;
    }

    public void setShiftName(String shiftName) {
        this.shiftName = shiftName;
    }

    @Transient
    public String getShiftName() {
        return shiftName;
    }

    public void setPosPCode(int posPCode) {
        this.posPCode = posPCode;
    }

    @Transient
    public int getPosPCode() {
        return posPCode;
    }

    @Override
    public String toString() {
        return getCposGroup().toString();// + " (" + getCposGroup().getCampusProgramOfStudy().getProgramOfStudy().getPCode() + ")";
    }

}
