package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import admission.enums.CategoryEnum;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AppliedCategory generated by hbm2java
 */
@Entity
@Table(name = "applied_category"
)
public class AppliedCategory implements java.io.Serializable {

    private Integer appliedCategoryId;
    private Candidate candidate;
    private String categoryCode;
    private CategoryEnum category;
    private String remarks;

    public AppliedCategory() {
    }

    public AppliedCategory(Candidate candidate) {
        this.candidate = candidate;
    }

    public AppliedCategory(Candidate candidate, String categoryCode, CategoryEnum category, String remarks) {
        this.candidate = candidate;
        this.categoryCode = categoryCode;
        this.category = category;
        this.remarks = remarks;
    }

    public AppliedCategory(String categoryCode, CategoryEnum category, String remarks) {
        this.categoryCode = categoryCode;
        this.category = category;
        this.remarks = remarks;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "applied_category_id", unique = true, nullable = false)
    public Integer getAppliedCategoryId() {
        return this.appliedCategoryId;
    }

    public void setAppliedCategoryId(Integer appliedCategoryId) {
        this.appliedCategoryId = appliedCategoryId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "candidate_id", nullable = false)
    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    @Column(name = "category_code", length = 5)
    public String getCategoryCode() {
        return this.categoryCode;
    }

    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    @Column(name = "code")
    @Enumerated(EnumType.ORDINAL)
    public CategoryEnum getCategory() {
        return category;
    }

    public void setCategory(CategoryEnum category) {
        this.category = category;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Override
    public String toString() {
        return categoryCode;
    }

}
