package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import admission.enums.JurisdictionEnum;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CampusProgramOfStudy generated by hbm2java
 */
@Entity
@Table(name = "campus_program_of_study"
)
public class CampusProgramOfStudy implements java.io.Serializable {

    private Integer programOfStudyId;
    private Integer shiftId;
    private Integer campusId;
    private boolean shiftIsMorning;

    private Integer campusProgramOfStudyId;
    private Shift shift;
    private Campus campus;
    private ProgramOfStudy programOfStudy;
    private Integer displayOrder;
    private String remarks;
    private JurisdictionEnum jurisdiction;
    private Boolean isSeperate;
    private Boolean isQuotaOriented;
    private Set<OtherTest> otherTests = new HashSet<OtherTest>(0);
    private Set<CandidateProgramOfStudy> candidateProgramOfStudies = new HashSet<CandidateProgramOfStudy>(0);
    private Set<CposGroup> cposGroups = new HashSet<CposGroup>(0);

    public CampusProgramOfStudy() {
    }

    public CampusProgramOfStudy(Shift shift, Campus campus, ProgramOfStudy programOfStudy) {
        this.shift = shift;
        this.campus = campus;
        this.programOfStudy = programOfStudy;
    }

    public CampusProgramOfStudy(Shift shift, Campus campus, ProgramOfStudy programOfStudy, Integer displayOrder, String remarks, JurisdictionEnum jurisdiction, Boolean isSeperate, Boolean isQuotaOriented, Set<OtherTest> otherTests, Set<CandidateProgramOfStudy> candidateProgramOfStudies, Set<CposGroup> cposGroups) {
        this.shift = shift;
        this.campus = campus;
        this.programOfStudy = programOfStudy;
        this.displayOrder = displayOrder;
        this.remarks = remarks;
        this.jurisdiction = jurisdiction;
        this.isSeperate = isSeperate;
        this.isQuotaOriented = isQuotaOriented;
        this.otherTests = otherTests;
        this.candidateProgramOfStudies = candidateProgramOfStudies;
        this.cposGroups = cposGroups;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "campus_program_of_study_id", unique = true, nullable = false)
    public Integer getCampusProgramOfStudyId() {
        return this.campusProgramOfStudyId;
    }

    public void setCampusProgramOfStudyId(Integer campusProgramOfStudyId) {
        this.campusProgramOfStudyId = campusProgramOfStudyId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "shift_id", nullable = false)
    public Shift getShift() {
        return this.shift;
    }

    public void setShift(Shift shift) {
        this.shift = shift;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "campus_id", nullable = false)
    public Campus getCampus() {
        return this.campus;
    }

    public void setCampus(Campus campus) {
        this.campus = campus;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "program_of_study_id", nullable = false)
    public ProgramOfStudy getProgramOfStudy() {
        return this.programOfStudy;
    }

    public void setProgramOfStudy(ProgramOfStudy programOfStudy) {
        this.programOfStudy = programOfStudy;
    }

    @Column(name = "display_order")
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }

    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "jurisdiction")
    @Enumerated
    public JurisdictionEnum getJurisdiction() {
        return this.jurisdiction;
    }

    public void setJurisdiction(JurisdictionEnum jurisdiction) {
        this.jurisdiction = jurisdiction;
    }

    @Column(name = "is_seperate")
    public Boolean getIsSeperate() {
        return this.isSeperate;
    }

    public void setIsSeperate(Boolean isSeperate) {
        this.isSeperate = isSeperate;
    }

    @Column(name = "is_quota_oriented")
    public Boolean getIsQuotaOriented() {
        return this.isQuotaOriented;
    }

    public void setIsQuotaOriented(Boolean isQuotaOriented) {
        this.isQuotaOriented = isQuotaOriented;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "campusProgramOfStudy")
    public Set<OtherTest> getOtherTests() {
        return this.otherTests;
    }

    public void setOtherTests(Set<OtherTest> otherTests) {
        this.otherTests = otherTests;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "campusProgramOfStudy")
    public Set<CandidateProgramOfStudy> getCandidateProgramOfStudies() {
        return this.candidateProgramOfStudies;
    }

    public void setCandidateProgramOfStudies(Set<CandidateProgramOfStudy> candidateProgramOfStudies) {
        this.candidateProgramOfStudies = candidateProgramOfStudies;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "campusProgramOfStudy")
    public Set<CposGroup> getCposGroups() {
        return this.cposGroups;
    }

    public void setCposGroups(Set<CposGroup> cposGroups) {
        this.cposGroups = cposGroups;
    }

    public void setCampusId(Integer campusId) {
        this.campusId = campusId;
    }

    public void setProgramOfStudyId(Integer programOfStudyId) {
        this.programOfStudyId = programOfStudyId;
    }

    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }

    @Transient
    public Integer getCampusId() {
        return campusId;
    }

    @Transient
    public Integer getProgramOfStudyId() {
        return programOfStudyId;
    }

    @Transient
    public Integer getShiftId() {
        return shiftId;
    }

    @Transient
    public boolean isShiftIsMorning() {
        return shiftIsMorning;
    }

    public void setShiftIsMorning(boolean shiftIsMorning) {
        this.shiftIsMorning = shiftIsMorning;
    }

    @Override
    public String toString() {
        return this.getProgramOfStudy().toString();
    }

}
