package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import admission.reports.beans.ProgramOfStudyDataBean;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CampusCategory generated by hbm2java
 */
@Entity
@Table(name = "campus_category"
)
public class CampusCategory implements java.io.Serializable {

    private int campusId;
    private boolean campusIsMain;
    private int categoryId;
    private int programTypeId;
    private int shiftId;
    private int categoryCode;
    private String categoryName;
    private String shiftName;
    private boolean morning;

    private List<ProgramOfStudyDataBean> listPosDb = new ArrayList<>();
    private List<AdmissionListDetails> newAld = new ArrayList<>();

    private Integer campusCategoryId;
    private Shift shift;
    private Category category;
    private ProgramType programType;
    private Campus campus;
    private Boolean onPercent;
    private Integer percent;
    private String remarks;
    private Integer displayOrder;
    private Set<DisciplineCategorySeats> disciplineCategorySeatses = new HashSet<DisciplineCategorySeats>(0);
    private Set<AdmissionListDetails> admissionListDetailses = new HashSet<AdmissionListDetails>(0);

    public CampusCategory() {
    }

    public CampusCategory(Category category, ProgramType programType, Campus campus) {
        this.category = category;
        this.programType = programType;
        this.campus = campus;
    }

    public CampusCategory(Shift shift, Category category, ProgramType programType, Campus campus, Boolean onPercent, Integer percent, String remarks, Integer displayOrder, Set<DisciplineCategorySeats> disciplineCategorySeatses, Set<AdmissionListDetails> admissionListDetailses) {
        this.shift = shift;
        this.category = category;
        this.programType = programType;
        this.campus = campus;
        this.onPercent = onPercent;
        this.percent = percent;
        this.remarks = remarks;
        this.displayOrder = displayOrder;
        this.disciplineCategorySeatses = disciplineCategorySeatses;
        this.admissionListDetailses = admissionListDetailses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "campus_category_id", unique = true, nullable = false)
    public Integer getCampusCategoryId() {
        return this.campusCategoryId;
    }

    public void setCampusCategoryId(Integer campusCategoryId) {
        this.campusCategoryId = campusCategoryId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "shift_id")
    public Shift getShift() {
        return this.shift;
    }

    public void setShift(Shift shift) {
        this.shift = shift;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_id", nullable = false)
    public Category getCategory() {
        return this.category;
    }

    public void setCategory(Category category) {
        this.category = category;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "program_type_id", nullable = false)
    public ProgramType getProgramType() {
        return this.programType;
    }

    public void setProgramType(ProgramType programType) {
        this.programType = programType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "campus_id", nullable = false)
    public Campus getCampus() {
        return this.campus;
    }

    public void setCampus(Campus campus) {
        this.campus = campus;
    }

    @Column(name = "on_percent")
    public Boolean getOnPercent() {
        return this.onPercent;
    }

    public void setOnPercent(Boolean onPercent) {
        this.onPercent = onPercent;
    }

    @Column(name = "percent")
    public Integer getPercent() {
        return this.percent;
    }

    public void setPercent(Integer percent) {
        this.percent = percent;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "display_order")
    public Integer getDisplayOrder() {
        return this.displayOrder;
    }

    public void setDisplayOrder(Integer displayOrder) {
        this.displayOrder = displayOrder;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "campusCategory")
    public Set<DisciplineCategorySeats> getDisciplineCategorySeatses() {
        return this.disciplineCategorySeatses;
    }

    public void setDisciplineCategorySeatses(Set<DisciplineCategorySeats> disciplineCategorySeatses) {
        this.disciplineCategorySeatses = disciplineCategorySeatses;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "campusCategory")
    public Set<AdmissionListDetails> getAdmissionListDetailses() {
        return this.admissionListDetailses;
    }

    public void setAdmissionListDetailses(Set<AdmissionListDetails> admissionListDetailses) {
        this.admissionListDetailses = admissionListDetailses;
    }

    @Transient
    public int getCampusId() {
        return campusId;
    }

    public void setCampusId(int campusId) {
        this.campusId = campusId;
    }

    @Transient
    public int getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(int categoryId) {
        this.categoryId = categoryId;
    }

    @Transient
    public int getProgramTypeId() {
        return programTypeId;
    }

    public void setProgramTypeId(int programTypeId) {
        this.programTypeId = programTypeId;
    }

    @Transient
    public int getShiftId() {
        return shiftId;
    }

    public void setShiftId(int shiftId) {
        this.shiftId = shiftId;
    }

    public void setCampusIsMain(boolean campusIsMain) {
        this.campusIsMain = campusIsMain;
    }

    @Transient
    public boolean isCampusIsMain() {
        return campusIsMain;
    }

    @Transient
    public int getCategoryCode() {
        return categoryCode;
    }

    public void setCategoryCode(int categoryCode) {
        this.categoryCode = categoryCode;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    @Transient
    public String getCategoryName() {
        return categoryName;
    }

    public void setListPosDb(List<ProgramOfStudyDataBean> listPosDb) {
        this.listPosDb = listPosDb;
    }

    @Transient
    public List<ProgramOfStudyDataBean> getListPosDb() {
        return listPosDb;
    }

    public void setMorning(boolean morning) {
        this.morning = morning;
    }

    @Transient
    public boolean isMorning() {
        return morning;
    }

    public void setShiftName(String shiftName) {
        this.shiftName = shiftName;
    }

    @Transient
    public String getShiftName() {
        return shiftName;
    }

    @Transient
    public List<AdmissionListDetails> getNewAld() {
        return newAld;
    }

    public void setNewAld(List<AdmissionListDetails> newAld) {
        this.newAld = newAld;
    }

    @Override
    public String toString() {
        if (this.category != null) {
            this.setCategoryName(category.toString());
        }
        return this.getCategoryName() + (this.getOnPercent() ? " " + this.getPercent() + "%" : "");
    }

}
