package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * CandidateProgramOfStudy generated by hbm2java
 */
@Entity
@Table(name = "candidate_program_of_study"
)
public class CandidateProgramOfStudy implements java.io.Serializable {

    private Integer campusProgramOfStudyId;
    private Integer candidateId;

    private Integer candidateProgramOfStudyId;
    private Candidate candidate;
    private CampusProgramOfStudy campusProgramOfStudy;
    private String remarks;
    private Integer choiceNo;
//    private Boolean isRecommed;
    private Set<AdmissionListDetails> admissionListDetailses = new HashSet<AdmissionListDetails>(0);

    public CandidateProgramOfStudy() {
    }

    public CandidateProgramOfStudy(Candidate candidate, CampusProgramOfStudy campusProgramOfStudy) {
        this.candidate = candidate;
        this.campusProgramOfStudy = campusProgramOfStudy;
    }

    public CandidateProgramOfStudy(Candidate candidate, CampusProgramOfStudy campusProgramOfStudy, String remarks, Integer choiceNo, Set<AdmissionListDetails> admissionListDetailses) {
        this.candidate = candidate;
        this.campusProgramOfStudy = campusProgramOfStudy;
        this.remarks = remarks;
        this.choiceNo = choiceNo;
        this.admissionListDetailses = admissionListDetailses;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "candidate_program_of_study_id", unique = true, nullable = false)
    public Integer getCandidateProgramOfStudyId() {
        return this.candidateProgramOfStudyId;
    }

    public void setCandidateProgramOfStudyId(Integer candidateProgramOfStudyId) {
        this.candidateProgramOfStudyId = candidateProgramOfStudyId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "candidate_id", nullable = false)
    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "campus_program_of_study_id", nullable = false)
    public CampusProgramOfStudy getCampusProgramOfStudy() {
        return this.campusProgramOfStudy;
    }

    public void setCampusProgramOfStudy(CampusProgramOfStudy campusProgramOfStudy) {
        this.campusProgramOfStudy = campusProgramOfStudy;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "choice_no")
    public Integer getChoiceNo() {
        return this.choiceNo;
    }

    public void setChoiceNo(Integer choiceNo) {
        this.choiceNo = choiceNo;
    }
    
//    @Column(name = "is_recommend")
//    public Boolean isRecommed() {
//        return isRecommed;
//    }
//
//    public void setIsRecommed(Boolean isRecommed) {
//        this.isRecommed = isRecommed;
//    }

    
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "candidateProgramOfStudy")
    public Set<AdmissionListDetails> getAdmissionListDetailses() {
        return this.admissionListDetailses;
    }

    public void setAdmissionListDetailses(Set<AdmissionListDetails> admissionListDetailses) {
        this.admissionListDetailses = admissionListDetailses;
    }

    @Transient
    public Integer getCampusProgramOfStudyId() {
        return campusProgramOfStudyId;
    }

    public void setCampusProgramOfStudyId(Integer campusProgramOfStudyId) {
        this.campusProgramOfStudyId = campusProgramOfStudyId;
    }

    @Transient
    public Integer getCandidateId() {
        return candidateId;
    }

    public void setCandidateId(Integer candidateId) {
        this.candidateId = candidateId;
    }

    @Override
    public String toString() {
        return campusProgramOfStudy.toString() + " (" + choiceNo + ")";//String.valueOf(this.candidateProgramOfStudyId);
    }

}
