package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import admission.enums.CategoryLogicalCodeEnum;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category"
)
public class Category implements java.io.Serializable {

    private Integer categoryId;
    private CategoryType categoryType;
    private String name;
    private CategoryLogicalCodeEnum categoryCode;
    private String PCode;
    private String remarks;
    private Set<CampusCategory> campusCategories = new HashSet<CampusCategory>(0);

    public Category() {
    }

    public Category(CategoryType categoryType) {
        this.categoryType = categoryType;
    }

    public Category(CategoryType categoryType, String name, CategoryLogicalCodeEnum categoryCode, String PCode, String remarks, Set<CampusCategory> campusCategories) {
        this.categoryType = categoryType;
        this.name = name;
        this.categoryCode = categoryCode;
        this.PCode = PCode;
        this.remarks = remarks;
        this.campusCategories = campusCategories;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "category_id", unique = true, nullable = false)
    public Integer getCategoryId() {
        return this.categoryId;
    }

    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "category_type_id", nullable = false)
    public CategoryType getCategoryType() {
        return this.categoryType;
    }

    public void setCategoryType(CategoryType categoryType) {
        this.categoryType = categoryType;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "code")
    @Enumerated(EnumType.ORDINAL)
    public CategoryLogicalCodeEnum getCategoryLogicalCodeEnum() {
        return this.categoryCode;
    }

    public void setCategoryLogicalCodeEnum(CategoryLogicalCodeEnum categoryCode) {
        this.categoryCode = categoryCode;
    }

    
    
    @Column(name = "p_code", length = 10)
    public String getPCode() {
        return this.PCode;
    }

    public void setPCode(String PCode) {
        this.PCode = PCode;
    }

    @Column(name = "remarks", length = 100)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "category")
    public Set<CampusCategory> getCampusCategories() {
        return this.campusCategories;
    }

    public void setCampusCategories(Set<CampusCategory> campusCategories) {
        this.campusCategories = campusCategories;
    }

    @Override
    public String toString() {
        return this.getName();
    }

}
