package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * DeptType generated by hbm2java
 */
@Entity
@Table(name = "dept_type"
)
public class DeptType implements java.io.Serializable {

    private Integer deptTypeId;
    private String name;
    private String remarks;
    private Set<Department> departments = new HashSet<Department>(0);

    public DeptType() {
    }

    public DeptType(String name, String remarks, Set<Department> departments) {
        this.name = name;
        this.remarks = remarks;
        this.departments = departments;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "dept_type_id", unique = true, nullable = false)
    public Integer getDeptTypeId() {
        return this.deptTypeId;
    }

    public void setDeptTypeId(Integer deptTypeId) {
        this.deptTypeId = deptTypeId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "deptType")
    @OrderBy("name")
    public Set<Department> getDepartments() {
        return this.departments;
    }

    public void setDepartments(Set<Department> departments) {
        this.departments = departments;
    }

    @Override
    public String toString() {
        return name;
    }

    
}
