package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * Discipline generated by hbm2java
 */
@Entity
@Table(name = "discipline"
)
public class Discipline implements java.io.Serializable {

    private Integer disciplineId;
    private Department department;
    private String name;
    private String code;
    private String remarks;
    private Set<ProgramOfStudy> programOfStudies = new HashSet<ProgramOfStudy>(0);
    private Set<Subject> subjects = new HashSet<Subject>(0);

    public Discipline() {
    }

    public Discipline(Department department) {
        this.department = department;
    }

    public Discipline(Department department, String name, String code, String remarks, Set<ProgramOfStudy> programOfStudies, Set<Subject> subjects) {
        this.department = department;
        this.name = name;
        this.code = code;
        this.remarks = remarks;
        this.programOfStudies = programOfStudies;
        this.subjects = subjects;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "discipline_id", unique = true, nullable = false)
    public Integer getDisciplineId() {
        return this.disciplineId;
    }

    public void setDisciplineId(Integer disciplineId) {
        this.disciplineId = disciplineId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "department_id", nullable = false)
    public Department getDepartment() {
        return this.department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "code", length = 10)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "discipline")
    @OrderBy("name")
    public Set<ProgramOfStudy> getProgramOfStudies() {
        return this.programOfStudies;
    }

    public void setProgramOfStudies(Set<ProgramOfStudy> programOfStudies) {
        this.programOfStudies = programOfStudies;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "discipline")
    @OrderBy("name")
    public Set<Subject> getSubjects() {
        return this.subjects;
    }

    public void setSubjects(Set<Subject> subjects) {
        this.subjects = subjects;
    }

    @Override
    public String toString() {
        return name;
    }
    
}
