package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * District generated by hbm2java
 */
@Entity
@Table(name = "district"
)
public class District implements java.io.Serializable {

    private Integer districtId;
    private Division division;
    private String name;
    private String remarks;
    private Set<Taluka> talukas = new HashSet<Taluka>(0);
    private Set<Jurisdiction> jurisdictions = new HashSet<Jurisdiction>(0);
    private Set<Candidate> candidates = new HashSet<Candidate>(0);

    public District() {
    }

    public District(Division division) {
        this.division = division;
    }

    public District(Division division, String name, String remarks, Set<Taluka> talukas, Set<Jurisdiction> jurisdictions, Set<Candidate> candidates) {
        this.division = division;
        this.name = name;
        this.remarks = remarks;
        this.talukas = talukas;
        this.jurisdictions = jurisdictions;
        this.candidates = candidates;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "district_id", unique = true, nullable = false)
    public Integer getDistrictId() {
        return this.districtId;
    }

    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "division_id", nullable = false)
    public Division getDivision() {
        return this.division;
    }

    public void setDivision(Division division) {
        this.division = division;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
    @OrderBy("name")
    public Set<Taluka> getTalukas() {
        return this.talukas;
    }

    public void setTalukas(Set<Taluka> talukas) {
        this.talukas = talukas;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
    public Set<Jurisdiction> getJurisdictions() {
        return this.jurisdictions;
    }

    public void setJurisdictions(Set<Jurisdiction> jurisdictions) {
        this.jurisdictions = jurisdictions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "district")
    public Set<Candidate> getCandidates() {
        return this.candidates;
    }

    public void setCandidates(Set<Candidate> candidates) {
        this.candidates = candidates;
    }

    @Override
    public String toString() {
        return name;
    }

    
}
