package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * DistrictSeatDistribution generated by hbm2java
 */
@Entity
@Table(name = "district_seat_distribution"
)
public class DistrictSeatDistribution implements java.io.Serializable, Cloneable{

    private Integer shiftId;
    private Integer admissionYearId;
    private Integer jurisdictionId;
    private Integer districtId;

    private Integer districtSeatDistributionId;
    private Shift shift;
    private Jurisdiction jurisdiction;
    private AdmissionYear admissionYear;
    private Integer urban;
    private Integer rural;
    private String remarks;
    private Integer other;

    public DistrictSeatDistribution() {
    }

    public DistrictSeatDistribution(Shift shift, Jurisdiction jurisdiction, AdmissionYear admissionYear) {
        this.shift = shift;
        this.jurisdiction = jurisdiction;
        this.admissionYear = admissionYear;
    }

    public DistrictSeatDistribution(Shift shift, Jurisdiction jurisdiction, AdmissionYear admissionYear, Integer urban, Integer rural, String remarks, Integer other) {
        this.shift = shift;
        this.jurisdiction = jurisdiction;
        this.admissionYear = admissionYear;
        this.urban = urban;
        this.rural = rural;
        this.remarks = remarks;
        this.other = other;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "district_seat_distribution_id", unique = true, nullable = false)
    public Integer getDistrictSeatDistributionId() {
        return this.districtSeatDistributionId;
    }

    public void setDistrictSeatDistributionId(Integer districtSeatDistributionId) {
        this.districtSeatDistributionId = districtSeatDistributionId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "shift_id", nullable = false)
    public Shift getShift() {
        return this.shift;
    }

    public void setShift(Shift shift) {
        this.shift = shift;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "jurisdiction_id", nullable = false)
    public Jurisdiction getJurisdiction() {
        return this.jurisdiction;
    }

    public void setJurisdiction(Jurisdiction jurisdiction) {
        this.jurisdiction = jurisdiction;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admission_year_id", nullable = false)
    public AdmissionYear getAdmissionYear() {
        return this.admissionYear;
    }

    public void setAdmissionYear(AdmissionYear admissionYear) {
        this.admissionYear = admissionYear;
    }

    @Column(name = "urban")
    public Integer getUrban() {
        return this.urban;
    }

    public void setUrban(Integer urban) {
        this.urban = urban;
    }

    @Column(name = "rural")
    public Integer getRural() {
        return this.rural;
    }

    public void setRural(Integer rural) {
        this.rural = rural;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "other")
    public Integer getOther() {
        return this.other;
    }

    public void setOther(Integer other) {
        this.other = other;
    }

    public void setAdmissionYearId(Integer admissionYearId) {
        this.admissionYearId = admissionYearId;
    }

    public void setDistrictId(Integer districtId) {
        this.districtId = districtId;
    }

    public void setJurisdictionId(Integer jurisdictionId) {
        this.jurisdictionId = jurisdictionId;
    }

    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }

    @Transient
    public Integer getAdmissionYearId() {
        return admissionYearId;
    }

    @Transient
    public Integer getDistrictId() {
        return districtId;
    }

    @Transient
    public Integer getJurisdictionId() {
        return jurisdictionId;
    }

    @Transient
    public Integer getShiftId() {
        return shiftId;
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        return super.clone(); //To change body of generated methods, choose Tools | Templates.
    }

    @Override
    public String toString() {
        return this.getJurisdiction().getDistrict().toString();
    }

}
