package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ForeignCandidate generated by hbm2java
 */
@Entity
@Table(name = "foreign_candidate"
)
public class ForeignCandidate implements java.io.Serializable {

    private Integer foreignCandidateId;
    private Candidate candidate;
    private String passportNo;
    private String placeOfIssue;
    private Date dated;
    private String visaNo;
    private Date visaNoDated;
    private Date dateOfValidity;
    private Date arrivalDateInPakistan;
    private String remarks;

    public ForeignCandidate() {
    }

    public ForeignCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    public ForeignCandidate(Candidate candidate, String passportNo, String placeOfIssue, Date dated, String visaNo, Date visaNoDated, Date dateOfValidity, Date arrivalDateInPakistan, String remarks) {
        this.candidate = candidate;
        this.passportNo = passportNo;
        this.placeOfIssue = placeOfIssue;
        this.dated = dated;
        this.visaNo = visaNo;
        this.visaNoDated = visaNoDated;
        this.dateOfValidity = dateOfValidity;
        this.arrivalDateInPakistan = arrivalDateInPakistan;
        this.remarks = remarks;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "foreign_candidate_id", unique = true, nullable = false)
    public Integer getForeignCandidateId() {
        return this.foreignCandidateId;
    }

    public void setForeignCandidateId(Integer foreignCandidateId) {
        this.foreignCandidateId = foreignCandidateId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "candidate_id", nullable = false)
    public Candidate getCandidate() {
        return this.candidate;
    }

    public void setCandidate(Candidate candidate) {
        this.candidate = candidate;
    }

    @Column(name = "passport_no", length = 45)
    public String getPassportNo() {
        return this.passportNo;
    }

    public void setPassportNo(String passportNo) {
        this.passportNo = passportNo;
    }

    @Column(name = "place_of_issue", length = 45)
    public String getPlaceOfIssue() {
        return this.placeOfIssue;
    }

    public void setPlaceOfIssue(String placeOfIssue) {
        this.placeOfIssue = placeOfIssue;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "dated", length = 10)
    public Date getDated() {
        return this.dated;
    }

    public void setDated(Date dated) {
        this.dated = dated;
    }

    @Column(name = "visa_no", length = 45)
    public String getVisaNo() {
        return this.visaNo;
    }

    public void setVisaNo(String visaNo) {
        this.visaNo = visaNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "visa_no_dated", length = 10)
    public Date getVisaNoDated() {
        return this.visaNoDated;
    }

    public void setVisaNoDated(Date visaNoDated) {
        this.visaNoDated = visaNoDated;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date_of_validity", length = 10)
    public Date getDateOfValidity() {
        return this.dateOfValidity;
    }

    public void setDateOfValidity(Date dateOfValidity) {
        this.dateOfValidity = dateOfValidity;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "arrival_date_in_pakistan", length = 10)
    public Date getArrivalDateInPakistan() {
        return this.arrivalDateInPakistan;
    }

    public void setArrivalDateInPakistan(Date arrivalDateInPakistan) {
        this.arrivalDateInPakistan = arrivalDateInPakistan;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

}
