package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Issuer generated by hbm2java
 */
@Entity
@Table(name = "issuer"
)
public class Issuer implements java.io.Serializable {

    private Integer issuerId;
    private String name;
    private String location;
    private String acronym;
    private String address;
    private Boolean isBoard;
    private Boolean isJurisdiction;
    private String remarks;
    private Integer code;

    public Issuer() {
    }

    public Issuer(String name, String location, String acronym, String address, Boolean isBoard, Boolean isJurisdiction, String remarks, Integer code) {
        this.name = name;
        this.location = location;
        this.acronym = acronym;
        this.address = address;
        this.isBoard = isBoard;
        this.isJurisdiction = isJurisdiction;
        this.remarks = remarks;
        this.code = code;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "issuer_id", unique = true, nullable = false)
    public Integer getIssuerId() {
        return this.issuerId;
    }

    public void setIssuerId(Integer issuerId) {
        this.issuerId = issuerId;
    }

    @Column(name = "name", length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "location", length = 45)
    public String getLocation() {
        return this.location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    @Column(name = "acronym", length = 20)
    public String getAcronym() {
        return this.acronym;
    }

    public void setAcronym(String acronym) {
        this.acronym = acronym;
    }

    @Column(name = "address", length = 100)
    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Column(name = "is_board")
    public Boolean getIsBoard() {
        return this.isBoard;
    }

    public void setIsBoard(Boolean isBoard) {
        this.isBoard = isBoard;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "code")
    public Integer getCode() {
        return this.code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    @Column(name = "is_jurisdiction")
    public Boolean getIsJurisdiction() {
        return isJurisdiction;
    }
    
    public void setIsJurisdiction(Boolean isJurisdiction) {
        this.isJurisdiction = isJurisdiction;
    }

    @Override
    public String toString() {
        return this.getLocation();
    }

}
