package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ProgramSubject generated by hbm2java
 */
@Entity
@Table(name = "optional_subject"
)
public class OptionalSubject implements java.io.Serializable {

    private Integer optionalSubjectId;
    private CredentialDetails credentialDetails;
    private Subject subject;
    private String remarks;

    public OptionalSubject() {
    }

    public OptionalSubject(Subject subject, CredentialDetails credentialDetails) {
        this.subject = subject;
        this.credentialDetails = credentialDetails;
    }

    public OptionalSubject(Subject subject, CredentialDetails credentialDetails, String remarks) {
        this.subject = subject;
        this.credentialDetails = credentialDetails;
        this.remarks = remarks;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "optional_subject_id", unique = true, nullable = false)
    public Integer getOptionalSubjectId() {
        return this.optionalSubjectId;
    }

    public void setOptionalSubjectId(Integer optionalSubjectId) {
        this.optionalSubjectId = optionalSubjectId;
    }
    

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id", nullable = false)
    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "credential_details_id", nullable = false)
    public CredentialDetails getCredentialDetails() {
        return this.credentialDetails;
    }

    public void setCredentialDetails(CredentialDetails credentialDetails) {
        this.credentialDetails = credentialDetails;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Override
    public String toString() {
        return this.getSubject().toString();
    }
}
