package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Prerequisite generated by hbm2java
 */
@Entity
@Table(name = "prerequisite"
)
public class Prerequisite implements java.io.Serializable {

    private Integer prerequisiteId;
    private ProgramSubject programSubject;
    private ProgramOfStudy programOfStudy;
    private Float percentage;
    private String remarks;

    public Prerequisite() {
    }

    public Prerequisite(ProgramSubject programSubject, ProgramOfStudy programOfStudy) {
        this.programSubject = programSubject;
        this.programOfStudy = programOfStudy;
    }

    public Prerequisite(ProgramSubject programSubject, ProgramOfStudy programOfStudy, Float percentage, String remarks) {
        this.programSubject = programSubject;
        this.programOfStudy = programOfStudy;
        this.percentage = percentage;
        this.remarks = remarks;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "prerequisite_id", unique = true, nullable = false)
    public Integer getPrerequisiteId() {
        return this.prerequisiteId;
    }

    public void setPrerequisiteId(Integer prerequisiteId) {
        this.prerequisiteId = prerequisiteId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "program_subject_id", nullable = false)
    public ProgramSubject getProgramSubject() {
        return this.programSubject;
    }

    public void setProgramSubject(ProgramSubject programSubject) {
        this.programSubject = programSubject;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "program_of_study_id", nullable = false)
    public ProgramOfStudy getProgramOfStudy() {
        return this.programOfStudy;
    }

    public void setProgramOfStudy(ProgramOfStudy programOfStudy) {
        this.programOfStudy = programOfStudy;
    }

    @Column(name = "percentage")
    public Float getPercentage() {
        return percentage;
    }

    public void setPercentage(Float percentage) {
        this.percentage = percentage;
    }
    
    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Override
    public String toString() {
        return this.getProgramSubject().toString();
    }

}
