package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;

/**
 * ProgramType generated by hbm2java
 */
@Entity
@Table(name = "program_type"
)
public class ProgramType implements java.io.Serializable {

    private Integer programTypeId;
    private String name;
    private Boolean isBachelor;
    private String remarks;

    public ProgramType() {
    }

    public ProgramType(String name, Boolean isBachelor, String remarks) {
        this.name = name;
        this.isBachelor = isBachelor;
        this.remarks = remarks;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "program_type_id", unique = true, nullable = false)
    public Integer getProgramTypeId() {
        return this.programTypeId;
    }

    public void setProgramTypeId(Integer programTypeId) {
        this.programTypeId = programTypeId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "is_bachelor")
    public Boolean getIsBachelor() {
        return this.isBachelor;
    }

    public void setIsBachelor(Boolean isBachelor) {
        this.isBachelor = isBachelor;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Override
    public String toString() {
        return name;
    }
}
