package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import admission.enums.DurationEnum;
import admission.enums.SemesterEnum;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProgramOfStudy generated by hbm2java
 */
@Entity
@Table(name = "program_of_study"
)
public class ProgramOfStudy implements java.io.Serializable {

    private Integer programOfStudyId;
    private Program program;
    private Discipline discipline;
    private String name;
    private Integer PCode;
    private DurationEnum duration;
    private SemesterEnum semester;
    private Boolean isQuotaOriented;
    private String remarks;
    private String code;
    private Set<CampusProgramOfStudy> campusProgramOfStudies = new HashSet<CampusProgramOfStudy>(0);
    private Set<Prerequisite> prerequisites = new HashSet<Prerequisite>(0);

    public ProgramOfStudy() {
    }

    public ProgramOfStudy(Program program, Discipline discipline, String code) {
        this.program = program;
        this.discipline = discipline;
        this.code = code;
    }

    public ProgramOfStudy(Program program, Discipline discipline, String name, Integer PCode, DurationEnum duration, SemesterEnum semester, Boolean isQuotaOriented, String remarks, String code, Set<CampusProgramOfStudy> campusProgramOfStudies, Set<Prerequisite> prerequisites) {
        this.program = program;
        this.discipline = discipline;
        this.name = name;
        this.PCode = PCode;
        this.duration = duration;
        this.semester = semester;
        this.isQuotaOriented = isQuotaOriented;
        this.remarks = remarks;
        this.code = code;
        this.campusProgramOfStudies = campusProgramOfStudies;
        this.prerequisites = prerequisites;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "program_of_study_id", unique = true, nullable = false)
    public Integer getProgramOfStudyId() {
        return this.programOfStudyId;
    }

    public void setProgramOfStudyId(Integer programOfStudyId) {
        this.programOfStudyId = programOfStudyId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "program_id", nullable = false)
    public Program getProgram() {
        return this.program;
    }

    public void setProgram(Program program) {
        this.program = program;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "discipline_id", nullable = false)
    public Discipline getDiscipline() {
        return this.discipline;
    }

    public void setDiscipline(Discipline discipline) {
        this.discipline = discipline;
    }

    @Column(name = "name", length = 200)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "p_code")
    public Integer getPCode() {
        return this.PCode;
    }

    public void setPCode(Integer PCode) {
        this.PCode = PCode;
    }

    @Column(name = "duration")
    @Enumerated(EnumType.ORDINAL)
    public DurationEnum getDuration() {
        return this.duration;
    }

    public void setDuration(DurationEnum duration) {
        this.duration = duration;
    }

    @Column(name = "semester")
    @Enumerated(EnumType.ORDINAL)
    public SemesterEnum getSemester() {
        return this.semester;
    }

    public void setSemester(SemesterEnum semester) {
        this.semester = semester;
    }

    @Column(name = "is_quota_oriented")
    public Boolean getIsQuotaOriented() {
        return this.isQuotaOriented;
    }

    public void setIsQuotaOriented(Boolean isQuotaOriented) {
        this.isQuotaOriented = isQuotaOriented;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "code", nullable = false, length = 10)
    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "programOfStudy")
    public Set<CampusProgramOfStudy> getCampusProgramOfStudies() {
        return this.campusProgramOfStudies;
    }

    public void setCampusProgramOfStudies(Set<CampusProgramOfStudy> campusProgramOfStudies) {
        this.campusProgramOfStudies = campusProgramOfStudies;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "programOfStudy")
    public Set<Prerequisite> getPrerequisites() {
        return this.prerequisites;
    }

    public void setPrerequisites(Set<Prerequisite> prerequisites) {
        this.prerequisites = prerequisites;
    }

    @Override
    public String toString() {
        return this.getName() + " (" + this.program.toString() + ")";
    }

}
