package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import admission.enums.LevelEnum;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Program generated by hbm2java
 */
@Entity
@Table(name = "program"
)
public class Program implements java.io.Serializable {

    private Integer programId;
    private ProgramType programType;
    private String name;
    private Boolean isDiscipline;
    private String remarks;
    private Integer periods;
    private LevelEnum level;
    private Set<ProgramSubject> programSubjects = new HashSet<ProgramSubject>(0);
    private Set<ProgramOfStudy> programOfStudies = new HashSet<ProgramOfStudy>(0);

    public Program() {
    }

    public Program(ProgramType programType) {
        this.programType = programType;
    }

    public Program(ProgramType programType, String name, Boolean isDiscipline, String remarks, Integer periods, LevelEnum level, Set<ProgramSubject> programSubjects, Set<ProgramOfStudy> programOfStudies) {
        this.programType = programType;
        this.name = name;
        this.isDiscipline = isDiscipline;
        this.remarks = remarks;
        this.periods = periods;
        this.level = level;
        this.programSubjects = programSubjects;
        this.programOfStudies = programOfStudies;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "program_id", unique = true, nullable = false)
    public Integer getProgramId() {
        return this.programId;
    }

    public void setProgramId(Integer programId) {
        this.programId = programId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "program_type_id", nullable = false)
    public ProgramType getProgramType() {
        return this.programType;
    }

    public void setProgramType(ProgramType programType) {
        this.programType = programType;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "is_discipline")
    public Boolean getIsDiscipline() {
        return this.isDiscipline;
    }

    public void setIsDiscipline(Boolean isDiscipline) {
        this.isDiscipline = isDiscipline;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Column(name = "periods")
    public Integer getPeriods() {
        return this.periods;
    }

    public void setPeriods(Integer periods) {
        this.periods = periods;
    }

    @Column(name = "level", length = 1)
    @Enumerated
    public LevelEnum getLevel() {
        return level;
    }

    public void setLevel(LevelEnum levelEnum) {
        this.level = levelEnum;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "program")
    public Set<ProgramSubject> getProgramSubjects() {
        return this.programSubjects;
    }

    public void setProgramSubjects(Set<ProgramSubject> programSubjects) {
        this.programSubjects = programSubjects;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "program")
    public Set<ProgramOfStudy> getProgramOfStudies() {
        return this.programOfStudies;
    }

    public void setProgramOfStudies(Set<ProgramOfStudy> programOfStudies) {
        this.programOfStudies = programOfStudies;
    }

    @Override
    public String toString() {
        return name;
    }
}
