package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProgramSubject generated by hbm2java
 */
@Entity
@Table(name = "program_subject"
)
public class ProgramSubject implements java.io.Serializable {

    private Integer programSubjectId;
    private Subject subject;
    private Program program;
    private String remarks;
    private Set<Prerequisite> prerequisites = new HashSet<Prerequisite>(0);

    public ProgramSubject() {
    }

    public ProgramSubject(Subject subject, Program program) {
        this.subject = subject;
        this.program = program;
    }

    public ProgramSubject(Subject subject, Program program, String remarks, Set<Prerequisite> prerequisites) {
        this.subject = subject;
        this.program = program;
        this.remarks = remarks;
        this.prerequisites = prerequisites;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "program_subject_id", unique = true, nullable = false)
    public Integer getProgramSubjectId() {
        return this.programSubjectId;
    }

    public void setProgramSubjectId(Integer programSubjectId) {
        this.programSubjectId = programSubjectId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "subject_id", nullable = false)
    public Subject getSubject() {
        return this.subject;
    }

    public void setSubject(Subject subject) {
        this.subject = subject;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "program_id", nullable = false)
    public Program getProgram() {
        return this.program;
    }

    public void setProgram(Program program) {
        this.program = program;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "programSubject")
    public Set<Prerequisite> getPrerequisites() {
        return this.prerequisites;
    }

    public void setPrerequisites(Set<Prerequisite> prerequisites) {
        this.prerequisites = prerequisites;
    }

    @Override
    public String toString() {
        return this.getSubject().getIsNone() ? program.toString() : getSubject().toString();
    }

}
