package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import admission.enums.ProvinceEnum;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Province generated by hbm2java
 */
@Entity
@Table(name = "province"
)
public class Province implements java.io.Serializable {

    private Integer provinceId;
    private String name;
    private ProvinceEnum code;
    private String remarks;
    private Set<Division> divisions = new HashSet<Division>(0);

    public Province() {
    }

    public Province(String name, ProvinceEnum code, String remarks, Set<Division> divisions) {
        this.name = name;
        this.code = code;
        this.remarks = remarks;
        this.divisions = divisions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "province_id", unique = true, nullable = false)
    public Integer getProvinceId() {
        return this.provinceId;
    }

    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "code")
    @Enumerated
    public ProvinceEnum getCode() {
        return this.code;
    }

    public void setCode(ProvinceEnum code) {
        this.code = code;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "province")
    public Set<Division> getDivisions() {
        return this.divisions;
    }

    public void setDivisions(Set<Division> divisions) {
        this.divisions = divisions;
    }

    @Override
    public String toString() {
        return name;
    }

    
}
