package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Religion generated by hbm2java
 */
@Entity
@Table(name = "religion"
)
public class Religion implements java.io.Serializable {

    private Integer religionId;
    private String name;
    private String remarks;
    private Set<Candidate> candidates = new HashSet<Candidate>(0);

    public Religion() {
    }

    public Religion(String name, String remarks, Set<Candidate> candidates) {
        this.name = name;
        this.remarks = remarks;
        this.candidates = candidates;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "religion_id", unique = true, nullable = false)
    public Integer getReligionId() {
        return this.religionId;
    }

    public void setReligionId(Integer religionId) {
        this.religionId = religionId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "religion")
    public Set<Candidate> getCandidates() {
        return this.candidates;
    }

    public void setCandidates(Set<Candidate> candidates) {
        this.candidates = candidates;
    }

    @Override
    public String toString() {
        return name;
    }

    
}
