package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Shift generated by hbm2java
 */
@Entity
@Table(name = "shift"
)
public class Shift implements java.io.Serializable {

    private Integer shiftId;
    private String name;
    private Boolean isMorning;
    private String remarks;
    private Set<DistrictSeatDistribution> districtSeatDistributions = new HashSet<DistrictSeatDistribution>(0);
    private Set<CampusCategory> campusCategories = new HashSet<CampusCategory>(0);
    private Set<CampusProgramOfStudy> campusProgramOfStudies = new HashSet<CampusProgramOfStudy>(0);

    public Shift() {
    }

    public Shift(String name, Boolean isMorning, String remarks, Set<DistrictSeatDistribution> districtSeatDistributions, Set<CampusCategory> campusCategories, Set<CampusProgramOfStudy> campusProgramOfStudies) {
        this.name = name;
        this.isMorning = isMorning;
        this.remarks = remarks;
        this.districtSeatDistributions = districtSeatDistributions;
        this.campusCategories = campusCategories;
        this.campusProgramOfStudies = campusProgramOfStudies;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "shift_id", unique = true, nullable = false)
    public Integer getShiftId() {
        return this.shiftId;
    }

    public void setShiftId(Integer shiftId) {
        this.shiftId = shiftId;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "is_morning")
    public Boolean getIsMorning() {
        return this.isMorning;
    }

    public void setIsMorning(Boolean isMorning) {
        this.isMorning = isMorning;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shift")
    public Set<DistrictSeatDistribution> getDistrictSeatDistributions() {
        return this.districtSeatDistributions;
    }

    public void setDistrictSeatDistributions(Set<DistrictSeatDistribution> districtSeatDistributions) {
        this.districtSeatDistributions = districtSeatDistributions;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shift")
    public Set<CampusCategory> getCampusCategories() {
        return this.campusCategories;
    }

    public void setCampusCategories(Set<CampusCategory> campusCategories) {
        this.campusCategories = campusCategories;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "shift")
    public Set<CampusProgramOfStudy> getCampusProgramOfStudies() {
        return this.campusProgramOfStudies;
    }

    public void setCampusProgramOfStudies(Set<CampusProgramOfStudy> campusProgramOfStudies) {
        this.campusProgramOfStudies = campusProgramOfStudies;
    }

    @Override
    public String toString() {
        return name;
    }
}
