package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Taluka generated by hbm2java
 */
@Entity
@Table(name = "taluka"
)
public class Taluka implements java.io.Serializable {

    private Integer talukaId;
    private District district;
    private String name;
    private String remarks;
//    private Set<Candidate> candidates = new HashSet<Candidate>(0);
    private Set<Jurisdiction> jurisdictions = new HashSet<Jurisdiction>(0);

    public Taluka() {
    }

    public Taluka(District district) {
        this.district = district;
    }

    public Taluka(District district, String name, String remarks, Set<Candidate> candidates, Set<Jurisdiction> jurisdictions) {
        this.district = district;
        this.name = name;
        this.remarks = remarks;
//        this.candidates = candidates;
        this.jurisdictions = jurisdictions;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "taluka_id", unique = true, nullable = false)
    public Integer getTalukaId() {
        return this.talukaId;
    }

    public void setTalukaId(Integer talukaId) {
        this.talukaId = talukaId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "district_id", nullable = false)
    public District getDistrict() {
        return this.district;
    }

    public void setDistrict(District district) {
        this.district = district;
    }

    @Column(name = "name", length = 45)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

//    @OneToMany(fetch = FetchType.LAZY, mappedBy = "taluka")
//    public Set<Candidate> getCandidates() {
//        return this.candidates;
//    }
//
//    public void setCandidates(Set<Candidate> candidates) {
//        this.candidates = candidates;
//    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "taluka")
    public Set<Jurisdiction> getJurisdictions() {
        return this.jurisdictions;
    }

    public void setJurisdictions(Set<Jurisdiction> jurisdictions) {
        this.jurisdictions = jurisdictions;
    }

    @Override
    public String toString() {
        return name;
    }

}
