package admission.model;
// Generated Jun 30, 2014 5:25:15 PM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Test generated by hbm2java
 */
@Entity
@Table(name = "test"
)
public class Test implements java.io.Serializable {

    private Integer testId;
    private ProgramType programType;
    private AdmissionYear admissionYear;
    private Campus campus;
    private Date date;
    private Date time;
    private String remarks;
    private Set<Candidate> candidates = new HashSet<Candidate>(0);

    public Test() {
    }

    public Test(ProgramType programType, AdmissionYear admissionYear, Campus campus) {
        this.programType = programType;
        this.admissionYear = admissionYear;
        this.campus = campus;
    }

    public Test(ProgramType programType, AdmissionYear admissionYear, Campus campus, Date date, Date time, String remarks, Set<Candidate> candidates) {
        this.programType = programType;
        this.admissionYear = admissionYear;
        this.campus = campus;
        this.date = date;
        this.time = time;
        this.remarks = remarks;
        this.candidates = candidates;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "test_id", unique = true, nullable = false)
    public Integer getTestId() {
        return this.testId;
    }

    public void setTestId(Integer testId) {
        this.testId = testId;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "program_type_id", nullable = false)
    public ProgramType getProgramType() {
        return this.programType;
    }

    public void setProgramType(ProgramType programType) {
        this.programType = programType;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "admission_year_id", nullable = false)
    public AdmissionYear getAdmissionYear() {
        return this.admissionYear;
    }

    public void setAdmissionYear(AdmissionYear admissionYear) {
        this.admissionYear = admissionYear;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "campus_id", nullable = false)
    public Campus getCampus() {
        return this.campus;
    }

    public void setCampus(Campus campus) {
        this.campus = campus;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "date", length = 10)
    public Date getDate() {
        return this.date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "time", length = 8)
    public Date getTime() {
        return this.time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    @Column(name = "remarks", length = 45)
    public String getRemarks() {
        return this.remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "test")
    public Set<Candidate> getCandidates() {
        return this.candidates;
    }

    public void setCandidates(Set<Candidate> candidates) {
        this.candidates = candidates;
    }

    @Override
    public String toString() {
        return programType.toString();
    }
    
}
